In [1]:
import ast
import re
import nltk
import pandas as pd
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [2]:
df = pd.read_csv('../data/raw/wiki_movie_plots_deduped.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 34886 entries, 0 to 34885
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Release Year      34886 non-null  int64
 1   Title             34886 non-null  str
 2   Origin/Ethnicity  34886 non-null  str
 3   Director          34886 non-null  str
 4   Cast              33464 non-null  str
 5   Genre             34886 non-null  str
 6   Wiki Page         34886 non-null  str
 7   Plot              34886 non-null  str
dtypes: int64(1), str(7)
memory usage: 78.9 MB

In [4]:
OriginsList = ['American','Canadian','Australian','Egyptian','British']
df['Origin/Ethnicity'].unique()

<ArrowStringArray>
[    'American',   'Australian',  'Bangladeshi',      'British',
     'Canadian',      'Chinese',     'Egyptian',    'Hong Kong',
     'Filipino',     'Assamese',      'Bengali',    'Bollywood',
      'Kannada',    'Malayalam',      'Marathi',      'Punjabi',
        'Tamil',       'Telugu',     'Japanese',    'Malaysian',
    'Maldivian',      'Russian', 'South_Korean',      'Turkish']
Length: 24, dtype: str

In [5]:
df.tail()

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot
34881,2014,The Water Diviner,Turkish,Director: Russell Crowe,Director: Russell Crowe\r\nCast: Russell Crowe...,unknown,https://en.wikipedia.org/wiki/The_Water_Diviner,"The film begins in 1919, just after World War ..."
34882,2017,Çalgı Çengi İkimiz,Turkish,Selçuk Aydemir,"Ahmet Kural, Murat Cemcir",comedy,https://en.wikipedia.org/wiki/%C3%87alg%C4%B1_...,"Two musicians, Salih and Gürkan, described the..."
34883,2017,Olanlar Oldu,Turkish,Hakan Algül,"Ata Demirer, Tuvana Türkay, Ülkü Duru",comedy,https://en.wikipedia.org/wiki/Olanlar_Oldu,"Zafer, a sailor living with his mother Döndü i..."
34884,2017,Non-Transferable,Turkish,Brendan Bradley,"YouTubers Shanna Malcolm, Shira Lazar, Sara Fl...",romantic comedy,https://en.wikipedia.org/wiki/Non-Transferable...,The film centres around a young woman named Am...
34885,2017,İstanbul Kırmızısı,Turkish,Ferzan Özpetek,"Halit Ergenç, Tuba Büyüküstün, Mehmet Günsür, ...",romantic,https://en.wikipedia.org/wiki/%C4%B0stanbul_K%...,The writer Orhan Şahin returns to İstanbul aft...

In [6]:
print((df['Genre'].str.lower() == 'unknown').sum())

6083

In [7]:
df = df.dropna(subset=['Plot', 'Genre'])
df = df[df['Genre'].str.lower() != 'unknown']
df.isna().sum()

Release Year          0
Title                 0
Origin/Ethnicity      0
Director              0
Cast                739
Genre                 0
Wiki Page             0
Plot                  0
dtype: int64

In [8]:
df.loc[(df['Origin/Ethnicity'].isin(['Egyptian']))]

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot
22896,1940,Yawm Said (Happy Day),Egyptian,Mohammed Karim,"Mohamed Abd El Wahab, Faten Hamama",drama,https://en.wikipedia.org/wiki/Yawm_Said,Abdel Wahab plays the role of a young man who ...
22897,1944,Rossassa Fel Qalb (Bullet in the Heart),Egyptian,Mohammed Karim,"Mohammed Abdel Wahab, Raqiya Ibrahim, Faten Ha...",drama,https://en.wikipedia.org/wiki/Rossassa_Fel_Qalb,Mohsen is a ladies' man. He has a close friend...
22898,1946,Malak al-Rahma (The Angel of Mercy),Egyptian,Youssef Wahbi,"Faten Hamama, Farid Shawki, Youssef Wahbi",drama,https://en.wikipedia.org/wiki/The_Angel_of_Mer...,Fouad Bek is married to Imtethal and has a dau...
22899,1947,Abu Zayd al-Hilali,Egyptian,Ezzel Dine Zulficar,"Seraj Munir, Faten Hamama",biography,https://en.wikipedia.org/wiki/Abu_Zayd_al-Hila...,Abu Zayd al-Hilali's son and wife escape and y...
22900,1948,Khulood (Immortality),Egyptian,Ezzel Dine Zulficar,"Kamal al-Shennawi, Faten Hamama, Ismail Yasseen",romance,https://en.wikipedia.org/wiki/Khulood,"A man named Mahmoud falls in love with Layla, ..."
...,...,...,...,...,...,...,...,...
22958,1992,Al-Irhab Wal Kabab (Terrorism and Kebab),Egyptian,Sherif Arafa,"Adel Emam, Yousra, Kamal el-Shennawi",political comedy,https://en.wikipedia.org/wiki/Terrorism_and_Kebab,The action primarily takes place in The Mogamm...
22959,1994,Al-Irhabi (The Terrorist),Egyptian,Nader Galal,"Adel Emam, Sherine, Madiha Yousri, Salah Zulfikar",political / drama,https://en.wikipedia.org/wiki/The_Terrorist_(1...,"Adel Imam plays Brother Ali, an Islamic radica..."
22960,1994,Al-Mohager (The Emigrant),Egyptian,Youssef Chahine,"Khaled El Nabawy, Hanan Tork, Youssra",drama,https://en.wikipedia.org/wiki/Al-Mohager,"In this film, young Ram is a thinker who has g..."
22961,1999,El Akhar (The Other),Egyptian,Youssef Chahine,"Nabila Ebeid, Mahmoud Hemida, Hanan Tork, Hani...",drama,https://en.wikipedia.org/wiki/The_Other_(1999_...,"Love sparks when Adam, back visiting Cairo fro..."
22962,1999,El Madina (The City),Egyptian,Yousry Nasrallah,Bassem Samra,drama,https://en.wikipedia.org/wiki/El_Madina,"In the center of El-Madina lives Ali, a young ..."

In [9]:
df.info()

<class 'pandas.DataFrame'>
Index: 28803 entries, 6 to 34885
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Release Year      28803 non-null  int64
 1   Title             28803 non-null  str
 2   Origin/Ethnicity  28803 non-null  str
 3   Director          28803 non-null  str
 4   Cast              28064 non-null  str
 5   Genre             28803 non-null  str
 6   Wiki Page         28803 non-null  str
 7   Plot              28803 non-null  str
dtypes: int64(1), str(7)
memory usage: 67.5 MB

In [10]:
df = df[df['Origin/Ethnicity'].isin(OriginsList)]

In [11]:
print(list(df['Origin/Ethnicity'].unique()))
df.info()

['American', 'Australian', 'British', 'Canadian', 'Egyptian']
<class 'pandas.DataFrame'>
Index: 21259 entries, 6 to 22962
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Release Year      21259 non-null  int64
 1   Title             21259 non-null  str
 2   Origin/Ethnicity  21259 non-null  str
 3   Director          21259 non-null  str
 4   Cast              20891 non-null  str
 5   Genre             21259 non-null  str
 6   Wiki Page         21259 non-null  str
 7   Plot              21259 non-null  str
dtypes: int64(1), str(7)
memory usage: 51.4 MB

In [12]:
list(df['Genre'].unique())

['western',
 'comedy',
 'short',
 'short action/crime western',
 'short film',
 'biographical',
 'drama',
 'adventure',
 'short fantasy',
 'silent sports',
 'horror',
 'crime',
 'drama, horror',
 'historical drama',
 'fantasy drama',
 'biographical drama',
 'documentary drama',
 'fantasy',
 'adventure serial',
 'epic',
 'historical',
 'comedy short',
 'comedy, western',
 'biography',
 'action adventure',
 'western drama',
 'short comedy',
 'comedy–drama',
 'romantic drama',
 'mystery',
 'crime drama',
 'romance',
 'sexual hygiene/exploitation film',
 'comedy drama',
 'war drama',
 'spy',
 'romantic comedy',
 'propaganda',
 'ww1 propaganda',
 'biopic',
 'animated series',
 'drama romance',
 'melodrama',
 'period drama',
 'swashbuckler',
 'romance drama',
 'drama, adventure',
 'crime comedy',
 'documentary',
 'comedy western',
 'fantasy, family',
 'war',
 'comedy, adventure',
 'fantasy, adventure',
 'thriller',
 'dramatic comedy',
 'romantic comedy/drama',
 'mystery, thriller',
 'crime thriller',
 'american football',
 'fantasy, romance',
 'comedy, horror, mystery',
 'semi-staged documentary',
 'biblical drama',
 'race film',
 'comedy adventure',
 'romance, drama',
 'comedy, romance',
 'crime, drama',
 'musical',
 'musical comedy',
 'operetta',
 'comedy mystery',
 'detective',
 'romance musical',
 'drama, war',
 'horror, comedy',
 'drama, crime',
 'musical, comedy',
 'costume drama',
 'prison drama',
 'spy drama',
 'comedy, drama',
 'action',
 'drama, western',
 'drama, thriller',
 'horror, science fiction',
 'romantic crime/mystery',
 'drama, musical',
 'film noir',
 'sports',
 'adventure film',
 'comedy, musical',
 'romantic',
 'drama, mystery',
 'animation',
 'science fiction',
 'comedy, crime',
 'drama, sports',
 'horror, sci-fi',
 'adventure, thriller',
 'crime, horror',
 'comedy, horror',
 'adventure, drama',
 'drama, romance',
 'comedy, fantasy',
 'science fiction, horror',
 'adventure horror',
 'animated',
 'historical comedy',
 'comedy, mystery',
 'comedy, drama, musical',
 'mystery, horror',
 'comedy romance',
 'romance, comedy',
 'comedy, drama, crime',
 'drama, biography',
 'drama, action',
 'sci-fi, horror',
 'adventure, action',
 'mystery, comedy',
 'drama, science fiction',
 'adventure, fantasy',
 'western, musical',
 'adventure, romance',
 'drama, sport',
 'musical biography',
 'western, war',
 'exploitation',
 'musical western',
 'murder mystery',
 'comedy 2-reeler',
 'comedy-drama',
 'action, western',
 'action, drama, war',
 'sport, drama',
 'serial',
 'sports drama',
 'drama, exploitation',
 'animated, musical',
 'military romance',
 'drama, fantasy',
 'western romance',
 'western, romance',
 'adventure, music',
 'drama, music',
 'mystery comedy',
 'western, comedy',
 'crime, film noir',
 'suspense',
 'gangster',
 'biblical',
 'epic drama',
 'bio-pic',
 'adventure drama',
 'musical romance',
 'musical fantasy',
 'crime, sci-fi',
 'comedy thriller',
 'war spy',
 'screwball comedy',
 'comedy spy',
 'science fiction horror',
 'spy thriller',
 'drama war',
 'horror comedy',
 'science fiction comedy',
 'animated short',
 'musical drama',
 'western musical',
 'sci-fi',
 'western serial',
 'family',
 'race',
 'charlie chan',
 'cartoon',
 'aviation',
 'action comedy',
 'western comedy',
 'war, biography',
 'war, romance',
 'crime musical',
 'fantasy thriller',
 'animated comedy',
 'musical biopic',
 'short animation',
 'docudrama',
 'spy serial',
 'drama, comedy; 6 separate stories',
 'war documentary',
 'propaganda short',
 'propaganda short animated short',
 'musical bio-pic',
 'drama anthology',
 'romantic fantasy',
 'musical–comedy',
 'horror, musical',
 'war comedy',
 'war drama propaganda',
 'drama, comedy',
 'crime, adventure',
 'romantic musical',
 'action western',
 'western, biography',
 'animated, war',
 'war propaganda',
 'biography, drama',
 'comedy, short',
 'fantasy, comedy',
 'war, drama',
 'animated, short',
 'crime mystery',
 'western, serial',
 'biography, crime',
 'war biography',
 'short subject',
 'family, drama',
 'family, western',
 'animated film',
 'experimental',
 'nature',
 'educational',
 'adventure, serial',
 'black comedy',
 'historic',
 'slapstick',
 'western, film noir',
 'comedy–horror',
 'historical epic',
 'rom com',
 'espionage',
 'musical, biography',
 'cold war',
 'biography, musical',
 'sports biopic',
 'adventures',
 'horror, 3-d',
 'thriller, 3-d',
 'sci-fi, 3-d',
 'western, 3-d',
 'science-fiction',
 'p.o.w.',
 'romance, trilogy',
 'action drama',
 'musical, drama',
 'western, drama',
 'war, western',
 'comedy, biography',
 'warner bros. drama',
 'sexploitation',
 'paramount. biblical epic',
 'spy film',
 'united artists. biography',
 'warner bros. biography',
 'disaster film',
 'war romance',
 'crime, western',
 'cartoon short',
 'drama, epic',
 'sci-fi comedy',
 'family comedy',
 'political drama',
 'disaster',
 'adult',
 'war short',
 'animated musical',
 'action, comedy',
 'epic western',
 'epic, biography',
 'political thriller',
 'comedy horror',
 'erotic comedy',
 'biography, war',
 'travel',
 'war, satire',
 'comedy, satire',
 'animated feature',
 'horror musical',
 'musical, fantasy',
 'neo-noir',
 'slasher',
 'spy anthology',
 'pow comedy',
 'musical, family',
 'family, comedy',
 'compilation',
 'comedy, action',
 'western, horror',
 'stop-motion animation',
 'crime, comedy',
 'experimental short',
 'spy film, comedy',
 'spy film, mystery',
 'comedy, parody',
 'outlaw biker film',
 'spy comedy',
 'biker drama',
 'biker film',
 'spy spoof',
 'western, mystery',
 'true crime',
 'biography, sports',
 'anthology',
 'biker',
 'musical, western',
 'war, comedy',
 'war, action',
 'comedy, war',
 'war, biker',
 'mockumentary',
 'psychological horror',
 'crime, action',
 'horror, action',
 'animated, adult',
 'sci-fi, comedy',
 'disaster film, adventure',
 'sci-fi, drama',
 'blaxploitation',
 'biography, crime drama',
 'martial arts',
 'crime, biography',
 'thriller, adventure',
 'adult film',
 'sci-fi, action',
 'science-fiction, thriller',
 'adult, horror',
 'drama, biographical',
 'comedy, sports',
 'sci-fi horror',
 'erotic musical',
 'horror, fantasy',
 'animated, family',
 'drama, television miniseries',
 'action, biography',
 'animated, fantasy',
 'drama, family',
 'fantasy, animated',
 'superhero film',
 'historical, erotic',
 'disaster film, sci-fi',
 'comedy, family',
 'sci-fi drama',
 'adventure, family',
 'action, war',
 'action, adventure',
 'fantasy, thriller',
 'fantasy, musical',
 'drama, animated',
 'mystery, drama',
 'comedy, anthology',
 'animation, family',
 'animation, adult',
 '16\xa0mm film',
 'action, fantasy',
 'science fiction, comedy',
 'teen',
 'superhero',
 'comedy, thriller',
 'parody',
 'thriller, crime',
 'horror, slasher',
 'action film',
 'family drama',
 'sports comedy',
 'horror, thriller',
 'erotic thriller',
 'action, horror',
 'sci-fi action',
 'science fiction, drama',
 'superhero, action',
 'comedy, cult',
 'cult film',
 'comedy, science fiction',
 'crime drama, comedy',
 'anthology, drama',
 'crime drama, action',
 'horror and priquitianism',
 'avant-garde',
 'action comedy, family',
 'animated, comedy',
 'crime, romance',
 'adventure, biography',
 'rom-com',
 'comedy, teen',
 'action thriller',
 'road thriller',
 'action, family',
 'family. drama',
 'comedy action',
 'action, drama',
 'biography, comedy',
 'family adventure',
 'action, science fiction',
 'science fiction, adventure',
 'clay animation',
 'family, fantasy',
 'science fiction, family',
 'science fiction, thriller',
 'imax',
 'student film',
 'biogtaphy, crime, drama',
 'family, mystery',
 'disaster, science fiction',
 'historical biopic',
 'action, sci-fi',
 'fantasy, sports',
 'action, superhero',
 'psychological thriller',
 'crime, thriller',
 'family, animated',
 'historical epic, disaster',
 'thriller, comedy',
 'science fiction, fantasy, action',
 "children's film",
 'family, animation',
 'science fiction thriller',
 'drama, biopic',
 'action-comedy, family',
 'animation, science fiction, drama, family',
 'comedy,horror',
 'shakespearean',
 'superhero comedy',
 'teen comedy',
 'animation, musical, comedy',
 'space opera',
 'animation comedy family',
 'comedy, drama, sports',
 'independent',
 'satire',
 'animation, adventure',
 'action, drama, epic,',
 'animation, fantasy',
 'comedy, sci-fi',
 'action, crime',
 'war, horror',
 'action, thriller',
 'reality',
 'drama, mystery, romance',
 'romance, war',
 'comedy-drama, fantasy',
 'comedy-drama, romance',
 'musical, romance',
 'live-action/animation',
 'fantasy, swashbuckler',
 'action film, war',
 'action, history',
 'crime, family',
 'disaster, sci-fi',
 'dramedy',
 'war film',
 'family, superhero',
 'western, romantic drama',
 'adventure, epic fantasy,',
 'animation, comedy',
 'science fiction, action',
 'fantasy, teen',
 'drama, silent',
 'action, 007',
 'fantasy adventure',
 'animation, musical',
 'action, spy',
 'horror, western',
 'dance',
 'drama, dance',
 'romance-horror',
 'martial arts/horror/comedy',
 'comedy/drama',
 'adventure/comedy/drama/family',
 'family, musical',
 'biography, western',
 'parody, sports',
 'dance, drama',
 'family, sports',
 'bio-pic, drama',
 'bio-pic, musical',
 'family, sci-fi',
 'comedy-drama, family',
 'adventure, swashbuckler',
 'musical, thriller',
 'fantasy, science fiction',
 'drama, martial arts',
 'adventure, mystery',
 'action, crime drama',
 'epic, science fiction',
 'science fiction, animated',
 'biography, horror',
 'dance, parody',
 'family, live-action/animated film',
 'fantasy, romantic comedy',
 'horror–thriller',
 'adventure, comedy',
 'black comedy, biography',
 'war, science fiction',
 'comedy horror, teen',
 'concert',
 'biography, romantic comedy',
 'romantic comedy, romantic',
 'dance, romance',
 'action, martial arts',
 'crime drama, biography',
 'family, science fiction',
 'action adventure, superhero',
 'animated, comedy, drama, family',
 'lgbt-themed comedy-drama',
 'horror, mystery',
 'political drama, thriller',
 'action-adventure, fantasy',
 'buddy cop, comedy',
 'dramedy, musical',
 'comedy, road',
 'fantasy romance',
 'biography, spy thriller',
 'action, spy film',
 'bio-pic, comedy-drama',
 'superhero, western',
 'drama comedy',
 'action-comedy',
 'action-adventure, fantasy, family',
 'dramedy, romance',
 'action thriller, fantasy',
 'action comedy, superhero',
 'action-comedy, parody',
 'family, live-action',
 'comedy, superhero',
 'comedy-drama, crime',
 'dark comedy',
 'action thriller, science fiction',
 'action horror, science fiction',
 'action-adventure',
 'action, romantic comedy',
 'crime thriller, drama',
 'sci-fi, thriller',
 'adventure, comedy, fantasy',
 'dance, drama, romance',
 'dramedy, thriller',
 'spoof',
 'drama, suspense thriller',
 'horror thriller',
 'romance, science fiction, thriller',
 'nature documentary',
 'fantasy, sci-fi drama',
 'romantic comedy, teen',
 'animated, family, fantasy',
 'drama, political thriller',
 'animated, family, spy film',
 'christian drama',
 'sci-fi western',
 'action thriller, sci-fi horror',
 'drama, spy thriller',
 'action, horror comedy',
 'adventure, historical drama',
 'supernatural horror, thriller',
 'dance, dramedy, romance',
 'drama, romantic comedy',
 'family, live action',
 'sci-fi, teen',
 'political drama, political thriller',
 'action drama, fantasy',
 'biopic, drama',
 'concert, documentary',
 'mystery, suspense thriller',
 'action, biopic',
 'animated, sci-fi comedy',
 'supernatural horror',
 'dark comedy, thriller',
 'action-adventure, family',
 'legal drama',
 'adventure, animated',
 'animated, family, western',
 'fantasy romance, horror',
 'adventure, disaster',
 'action, mystery',
 'drama, teen',
 'family, spy film',
 'dark comedy, superhero',
 'anthology, horror comedy',
 'parody, horror',
 'supernatural thriller',
 'family, animated, fantasy',
 'social',
 'family film',
 'family, romantic drama',
 'family, direct-to-dvd',
 'adventure, animated, fantasy',
 'adventure, drama, epic',
 'crime drama, superhero',
 'family film, direct-to-dvd',
 'animated, horror comedy',
 'action thriller, adventure drama',
 'action drama, science fiction',
 'crime thriller, dark comedy',
 'drama, gangster',
 'action-adventure, drama',
 'biopic, political drama',
 'dramedy, fantasy',
 'animated, horror comedy, thriller',
 'dramedy, teen',
 'action, horror, science fiction',
 'action drama, war',
 'action-adventure, animated, family',
 'musical, romantic comedy',
 'animated, family, 3d',
 'comedy, spy film',
 'family, sports comedy',
 'drama, coming of age',
 'anthology, horror',
 'animated, comedy, family',
 'drama, independent movie',
 'bio-pic, sports',
 'horror-thriller',
 'survival',
 'action drama, bio-pic, thriller',
 'historical, music',
 'adventure, animated, comedy',
 'action-thriller',
 'crime thriller, neo-noir',
 'adventure, animated, family, fantasy-comedy',
 'animated, sci-fi',
 'animated, buddy comedy',
 'animated, fantasy, musical',
 'bio-pic, drama, music',
 'boxing, comedy',
 'action-adventure, horror',
 'slahser',
 'horror comedy, parody',
 'buddy cop',
 'romance, sci-fi',
 'action drama, sci-fi',
 'dark comedy, horror',
 'animated, superhero',
 'biographical, documentary',
 'comedy, documentary',
 'action-adventure, western',
 'biographical, drama',
 'documentary, music',
 'crime, dark comedy',
 'fantasy-comedy',
 'buddy cop, supernatural',
 'romantic thriller',
 'comedy-drama, crime thriller',
 'action-adventure, sci-fi',
 'comedy-drama, teen',
 'thriller, western',
 'action, comedy-drama',
 'documentary, family',
 'horror, romantic comedy',
 'bio-pic, black comedy',
 'romantic-comedy',
 'christian',
 'animation adventure',
 'animation comedy',
 'animation fantasy',
 'animated adventure',
 'romance thriller',
 'romantic comedy-drama',
 'science fiction psychological thriller ',
 'drama horror thriller film',
 'science fiction mystery',
 'anime',
 'biographical drama ',
 'adventure science fiction',
 'crime comedy-drama ',
 'action adventure science fiction',
 'adventure thriller',
 'adventure-comedy',
 'biographical comedy-drama',
 'western thriller',
 'biographical political thriller',
 'animation martial arts action-comedy',
 'comedy-horror',
 'fantasy action',
 'science fiction psychological thriller',
 'romance dramedy',
 'science fiction adventure',
 'science fiction drama supernatural',
 'science fiction action',
 'fantasy action adventure',
 'superhero action adventure',
 'science fiction action-comedy',
 'mockumentary comedy',
 'social science fiction action',
 'supernatural comedy',
 'science fiction action adventure',
 'action adventure thriller spy',
 'crime dramedy',
 "auli'i cravalho dwayne johnson",
 'reese witherspoon scarlett johansson',
 'animation, adventure, sci-fi',
 'horror, thriller, drama',
 'crime, drama, thriller',
 'action, adventure, horror, sci-fi',
 'sci-fi, adventure, romance',
 'animation, comedy, action',
 'neo-noir, action, thriller',
 'thriller, fantasy',
 'horror, suspense',
 'action, crime, drama',
 'post-apocalyptic, zombie',
 'action, adventure, superhero, drama',
 'action, adventure, fantasy, sci-fi',
 'fantasy, adventure, musical, drama, romance',
 'action, horror, thriller',
 'action, adventure, drama, superhero',
 'action, adventure, crime, sci-fi',
 'romance, drama, sci-fi',
 'animation, comedy, fantasy, family',
 'sci-fi, animation, comedy',
 'sci-fi, drama, thriller',
 'superhero, comedy, adventure, sci-fi',
 'action, adventure, epic',
 'action, adventure, fantasy, comedy',
 'comedy, drama, war',
 'superhero, action, adventure, fantasy, drama, war',
 'animation, action, comedy, family',
 'comedy, drama, romance',
 'action, adventure, fantasy, horror',
 ' usa, can ',
 'animation, sports, comedy, drama',
 'action, adventure, sci-fi',
 'romance, comedy, drama',
 'romance, horror, thriller',
 'comedy, action, crime',
 'action, adventure, drama, fantasy',
 'animation, comedy, adventure, action',
 'drama, fantasy, horror, romance',
 'action, adventure, superhero, comedy, sci-fi',
 'sci-fi, adventure, drama, action',
 'thriller, horror',
 'sci-fi, action, adventure',
 'thriller, action',
 'animation, comedy, adventure',
 'action, fantasy, adventure, horror, sci-fi, western',
 'thriller, sci-fi, action',
 ' usa ',
 'horror, fantasy, drama',
 'action, adventure, comedy',
 'animation, action, comedy, martial arts',
 'biography, sports, comedy, drama',
 'biography, action, comedy, crime, drama, history, thriller',
 'horror, sci-fi, drama',
 'neo-noir, sci-fi, thriller, mystery',
 'romance, disaster',
 'animation, adventure, comedy, family, fantasy, musical',
 'drama, action, thriller',
 'horror, mystery, thriller',
 'biography, drama, thriller',
 'action, sci-fi, thriller',
 'action, biography, drama',
 'comedy, drama, horror, mystery, thriller',
 'biography, war, drama',
 'crime, comedy, drama, mystery, thriller',
 'crime, horror, mystery, thriller',
 'superhero, action, adventure, fantasy, sci-fi, comedy',
 'mystery, crime, drama',
 'comedy, crime, drama, thriller',
 'action, horror, comedy',
 'superhero, action, adventure, fantasy, sci-fi',
 'animation, adventure, comedy',
 'animation, musical, fantasy, mystery',
 'biography, comedy, drama',
 'fantasy, horror, romance, sci-fi, thriller',
 'animation, adventure, comedy, family',
 'sci-fi, action, thriller',
 'action, fantasy, adventure, comedy',
 'biography, musical, drama',
 'sci-fi, comedy, drama',
 'biography, drama, history, thriller',
 'action, fantasy, sci-fi',
 'crime, drama, mystery',
 'biography, crime, drama',
 'action/ drama/ thriller',
 'drama / thriller',
 'comedy / sci-fi',
 'drama / history / war',
 'comedy / horror',
 'short documentary',
 'mystery drama',
 'comedy / western',
 'drama / romance',
 'comedy / drama',
 'music',
 'action / drama',
 'fantasy / thriller',
 'surf / thriller',
 'adventure / family / drama',
 'horror / mystery / thriller',
 'drama / history',
 'crime / drama',
 'imdb',
 'animation, live action / drama / comedy',
 'action / adventure',
 'biography / drama / romance',
 'action / drama / war',
 'drama / adventure',
 'adventure / musical',
 'action / comedy',
 'musical / fantasy / comedy',
 'horror / thriller',
 'animation / adventure',
 'action / sci-fi / adventure',
 'adventure / comedy',
 'science fiction/action',
 'historical romance',
 'adventure, crime, drama',
 'war / drama',
 'horror / drama',
 'action / adventure / comedy',
 'adventure / drama / western',
 'post-apocalyptic science fiction',
 'black comedy / romance',
 'drama / war',
 'adventure/ drama/ history',
 'biography / drama',
 'drama / science-fiction',
 'action / science-fiction',
 'comedy / thriller',
 "children's",
 'action / crime / drama',
 'crime / drama / thriller',
 'drama / comedy / romance',
 'biography crime',
 'animation musical',
 'comedy short film',
 'short/drama/mystery (30min)',
 'drama/horror/thriller',
 'supernatural action',
 'adventure, romantic drama',
 'pseudo-documentary, psychological horror',
 'animation drama',
 'biography drama',
 'family, adventure',
 'erotic drama',
 'apocalyptic thriller',
 'biographical war film',
 'drama, true crime',
 'romance/drama',
 'world war i',
 'romance/adventure',
 'historical/drama',
 'war/drama',
 'mystery/thriller',
 'spy/world war i',
 'romantic adventure',
 'comedy/musical',
 'romance/comedy',
 'comedy/romance',
 'romance/musical',
 'drama/romance',
 'mystery/horror',
 'spy/drama',
 'musical/drama',
 'war/romance',
 'adventure/romance',
 'comedy/crime',
 'action/comedy',
 'musical/comedy',
 'world war ii',
 'war/spy',
 'fantasy/adventure',
 'comedy/thriller',
 'world war ii documentary',
 'world war ii/drama',
 'world war ii drama documentary',
 'shakespearean drama',
 'family/adventure',
 'literary drama',
 'australian western',
 'sports/comedy',
 'short mystery',
 'action based on radio serial',
 'romance/fantasy',
 'adventure/biopic',
 'comedy based on comic strip',
 'south african western',
 'drama/thriller',
 'world war ii/comedy',
 'african drama',
 'science fiction/comedy',
 'drama documentary',

In [13]:
GENRE_MAP = {
    'science fiction': 'sci-fi',
    'romantic comedy': 'rom-com',
    'romantic': 'romance',
    'biographical': 'biography',
    'biopic': 'biography',
}


def cleanGenre(g):
    g = str(g).lower()
    for key, val in GENRE_MAP.items():
        g = g.replace(key, val)
    g = re.sub(r'\b(film|short|series|serial|movie)\b', '', g)

    
    genres = re.split(r'[/,&\s]+', g)
    return [x for x in genres if len(x) > 2]


df['GenreList'] = df['Genre'].apply(cleanGenre)

allGenres = [g for sub in df['GenreList'] for g in sub]
Top15 = pd.Series(allGenres).value_counts().head(20).index.tolist()

df['GenreList'] = df['GenreList'].apply(
    lambda list_: [g for g in list_ if g in Top15]
)
df = df[df['GenreList'].map(len) > 0]
print(Top15)

['drama', 'comedy', 'crime', 'horror', 'thriller', 'western', 'action', 'musical', 'sci-fi', 'adventure', 'war', 'romance', 'animated', 'mystery', 'biography', 'family', 'rom-com', 'noir', 'fantasy', 'animation']

In [14]:
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))


def lemmatize_plot(text):
    clean_text = re.sub(r'[^a-z\s]', '', str(text).lower())
    words = clean_text.split()

    clean_words = [
        lemmatizer.lemmatize(lemmatizer.lemmatize(w, pos='v'), pos='n')
        for w in words
        if w not in stop_words
    ]
    return ' '.join(clean_words)


df['CleanPlot'] = df['Plot'].apply(lemmatize_plot)

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 20233 entries, 6 to 22962
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Release Year      20233 non-null  int64
 1   Title             20233 non-null  str
 2   Origin/Ethnicity  20233 non-null  str
 3   Director          20233 non-null  str
 4   Cast              19920 non-null  str
 5   Genre             20233 non-null  str
 6   Wiki Page         20233 non-null  str
 7   Plot              20233 non-null  str
 8   GenreList         20233 non-null  object
 9   CleanPlot         20233 non-null  str
dtypes: int64(1), object(1), str(8)
memory usage: 77.7+ MB

In [16]:
df.head()

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot,GenreList,CleanPlot
6,1903,The Great Train Robbery,American,Edwin S. Porter,NaN,western,https://en.wikipedia.org/wiki/The_Great_Train_...,The film opens with two bandits breaking into ...,[western],film open two bandit break railroad telegraph ...
7,1904,The Suburbanite,American,Wallace McCutcheon,NaN,comedy,https://en.wikipedia.org/wiki/The_Suburbanite,The film is about a family who move to the sub...,[comedy],film family move suburb hop quiet life thing s...
11,1906,From Leadville to Aspen: A Hold-Up in the Rockies,American,Francis J. Marion and Wallace McCutcheon,NaN,short action/crime western,https://en.wikipedia.org/wiki/From_Leadville_t...,The film features a train traveling through th...,"[action, crime, western]",film feature train travel rockies hold create ...
13,1907,Daniel Boone,American,Wallace McCutcheon and Ediwin S. Porter,"William Craven, Florence Lawrence",biographical,https://en.wikipedia.org/wiki/Daniel_Boone_(19...,Boone's daughter befriends an Indian maiden as...,[biography],boone daughter befriend indian maiden boone co...
14,1907,How Brown Saw the Baseball Game,American,Unknown,Unknown,comedy,https://en.wikipedia.org/wiki/How_Brown_Saw_th...,Before heading out to a baseball game at a nea...,[comedy],head baseball game nearby ballpark sport fan m...

In [17]:

df[['Title', 'Release Year', 'Director', 'GenreList', 'Plot', 'CleanPlot']].to_parquet(
    '../data/processed/plotify_cleaned_movies.parquet', index=False
)